import React,{useCallback,useEffect,useRef,useState}from'react';
import{ArrowLeftRight,Check,Coins,Loader2,X}from'lucide-react';
import Pusher from'pusher-js';
import{api}from'../../utils/api';
const STATUS={pending:'En attente',accepted:'Accepté',declined:'Refusé',cancelled:'Annulé'};
function Row({trade,onAction,busy}){const incoming=trade.direction==='incoming',other=incoming?trade.proposer:trade.recipient;return <article className="trade-inbox__row"><div className="trade-inbox__row-head"><strong>{other.username}<small>#{other.discriminator}</small></strong><span className={`trade-status trade-status--${trade.status}`}>{STATUS[trade.status]}</span></div><div className="trade-inbox__cards"><span><small>{incoming?'Vous recevez':'Vous offrez'}</small><strong>{trade.offered_card.name}</strong><em>{trade.offered_card.rarity}</em></span><ArrowLeftRight size={15}/><span><small>{incoming?'Vous donnez':'Vous demandez'}</small><strong>{trade.requested_card.name}</strong><em>{trade.requested_card.rarity}</em></span></div>{trade.coin_fee>0&&<p><Coins size={13}/>{trade.viewer_pays_fee?`Vous payez ${trade.coin_fee} pièces`:`${other.username} paie ${trade.coin_fee} pièces`}</p>}{trade.status==='pending'&&<div className="trade-inbox__actions">{incoming?<><button className="btn-primary" disabled={busy} onClick={()=>onAction(trade.id,'accept')}><Check size={14}/>Accepter</button><button className="btn-secondary" disabled={busy} onClick={()=>onAction(trade.id,'decline')}><X size={14}/>Refuser</button></>:<button className="btn-secondary" disabled={busy} onClick={()=>onAction(trade.id,'cancel')}><X size={14}/>Annuler</button>}</div>}</article>}
export default function TradeInbox({user}){
 const[open,setOpen]=useState(false),[data,setData]=useState({incoming:[],outgoing:[],pending_count:0}),[tab,setTab]=useState('incoming'),[busy,setBusy]=useState(null),[loading,setLoading]=useState(false);const pusherRef=useRef(null);
 const load=useCallback(async(quiet=false)=>{if(!quiet)setLoading(true);try{setData(await api.get('/trades'))}catch(e){console.error(e)}finally{if(!quiet)setLoading(false)}},[]);
 useEffect(()=>{load(true);const timer=setInterval(()=>load(true),30000);return()=>clearInterval(timer)},[load]);
 useEffect(()=>{if(!data.pusher_key||!user?.id||pusherRef.current)return;const p=new Pusher(data.pusher_key,{cluster:data.pusher_cluster||'eu'}),channel=p.subscribe(`user-${user.id}`);['trade_created','trade_accepted','trade_declined','trade_cancelled'].forEach(event=>channel.bind(event,()=>{load(true);window.dispatchEvent(new Event('trade_inventory_changed'))}));pusherRef.current=p;return()=>{p.disconnect();pusherRef.current=null}},[data.pusher_key,data.pusher_cluster,user?.id,load]);
 const act=async(id,action)=>{setBusy(id);try{if(action==='cancel')await api.post('/trades/cancel',{trade_id:id});else await api.post('/trades/respond',{trade_id:id,action});await load(true);window.dispatchEvent(new Event('trade_inventory_changed'))}catch(e){alert(e.message)}finally{setBusy(null)}};
 const trades=data[tab]||[];
 return <div className="trade-inbox"><button className="app-header__icon trade-inbox__trigger" onClick={e=>{e.stopPropagation();setOpen(v=>!v);if(!open)load()}} aria-label="Mes échanges"><ArrowLeftRight size={18}/>{data.pending_count>0&&<span>{data.pending_count}</span>}</button>{open&&<div className="trade-inbox__panel" onClick={e=>e.stopPropagation()}><header><div><span className="kicker">Marché privé</span><h3>Mes échanges</h3></div><button className="trade-close" onClick={()=>setOpen(false)}><X size={17}/></button></header><div className="trade-inbox__tabs"><button className={tab==='incoming'?'active':''} onClick={()=>setTab('incoming')}>Reçus {data.pending_count>0&&<span>{data.pending_count}</span>}</button><button className={tab==='outgoing'?'active':''} onClick={()=>setTab('outgoing')}>Envoyés</button></div><div className="trade-inbox__list">{loading?<div className="trade-loading"><Loader2 className="animate-spin"/></div>:trades.length?trades.map(t=><Row key={t.id} trade={t} onAction={act} busy={busy===t.id}/>):<p className="trade-empty">Aucun échange dans cette catégorie.</p>}</div></div>}</div>;
}
